//
//  CityData.swift
//  EmpikTestApp
//
//  Created by Michael on 7/29/23.
//

import Foundation

struct CityData {
    static let a = ["Abidjan", "Abu Dhabi", "Accra", "Acheng", "Ad-dammam", "Adana", "Addis Ababa", "Adelaide", "Agra", "Aguascalientes", "Ahmedabad", "Ahwaz", "Aleppo", "Alexandria", "Algiers", "Aligarh", "Allahabad", "Almaty", "Amman", "Amravati", "Amritsar", "Amsterdam", "Ankang", "Ankara", "Anlu", "Anqing", "Anqiu", "Anshan", "Anshun", "Antalya", "Antananarivo", "Anyang", "Arequipa", "Asansol", "Astana", "Asuncion", "Athens", "Atlanta", "Auckland", "Aurangabad", "Austin"]
    static let b = ["Baghdad", "Baku", "Baltimore", "Bamako", "Bandar Lampung", "Bandung", "Bangalore", "Bangkok", "Baoding", "Baoji", "Baoshan", "Baotou", "Barcelona", "Bareilly", "Barnaul", "Barquisimeto", "Barranquilla", "Bazhong", "Bazhou", "Beihai", "Beijing", "Beiliu", "Beipiao", "Belgrade", "Belo Horizonte", "Belem", "Bengbu", "Benghazi", "Benin City", "Benxi", "Berlin", "Bhilai Nagar", "Bhiwandi", "Bhopal", "Bhubaneswar", "Bijie", "Bikaner", "Binzhou", "Birmingham", "Bishkek", "Bogor", "Bonn", "Boston", "Botou", "Bozhou", "Brasilia", "Bremen", "Brisbane", "Bristol", "Brussels", "Bucharest", "Bucheon", "Budapest", "Buenos Aires", "Bulawayo", "Bursa", "Busan", "Beni-mellal"]
    static let c = ["Cairo", "Calgary", "Cali", "Callao", "Caloocan", "Campinas", "Campo Grande", "Cancun", "Cape Town", "Caracas", "Cartagena", "Casablanca", "Cebu", "Cenxi", "Chandigarh", "Changchun", "Changde", "Changle", "Changning", "Changsha", "Changshu", "Changyi", "Changzhi", "Changzhou", "Chaohu", "Chaoyang", "Charlotte", "Chelyabinsk", "Chengdu", "Chenghai", "Chenzhou", "Cheongju", "Chiba", "Chicago", "Chifeng", "Chihuahua", "Chittagong", "Chizhou", "Chon Buri", "Chongjin", "Chongqing", "Chongzhou", "Ciudad Guayana", "Cochabamba", "Coimbatore", "Colombo", "Colombo", "Columbus", "Conakry", "Contagem", "Cotonou", "Cuernavaca", "Cuiaba", "Culiacan Rosales", "Curitiba", "Cuttack", "Cordoba", "Cucuta"]
    static let d = ["Daegu", "Daejeon", "Dafeng", "Dakar", "Dali", "Dalian", "Dallas", "Damascus", "Dandong", "Danyang", "Dar es Salaam", "Dashiqiao", "Datong", "Davao", "Daye", "De Juarez", "Dehradun", "Dehui", "Deir El-zor", "Delhi", "Dengfeng", "Dengzhou", "Denver", "Detroit", "Deyang", "Dezhou", "Dhaka", "Dhanbad", "Dingzhou", "Diyarbakir", "Dnipropetrovsk", "Donggang", "Dongguan", "Dongtai", "Dongyang", "Dongying", "Dortmund", "Douala", "Dubai", "Dublin", "Duisburg", "Dujiangyan", "Duque de Caxias", "Durban", "Dushanbe", "Dusseldorf"]
    static let e = ["Edmonton", "El Alto", "El Paso", "El-jadida", "Enshi", "Esfahan", "Essen", "Ezhou"]
    static let f = ["Faisalabad", "Faridabad", "Feicheng", "Feira de Santana", "Fengcheng", "Fengcheng", "Fengnan", "Fort Worth", "Fortaleza", "Foshan", "Frankfurt am Main", "Fuan", "Fuding", "Fukuoka", "Funabashi", "Fuqing", "Fushun", "Fuxin", "Fuyang", "Fuyang", "Fuzhou", "Fuzhou", "Fès"]
    static let g = ["Gaizhou", "Gaoan", "Gaobeidian", "Gaocheng", "Gaomi", "Gaoyao", "Gaoyou", "Gaozhou", "Gaziantep", "Genova", "Ghaziabad", "Giza", "Glasgow", "Goiânia", "Gongyi", "Gongzhuling", "Gorakhpur", "Goyang", "Guadalajara", "Guanghan", "Guangshui", "Guangyuan", "Guangzhou", "Guarulhos", "Guatemala City", "Guayaquil", "Guigang", "Guilin", "Guiping", "Guixi", "Guiyang", "Gujranwala", "Guwahati", "Gwalior", "Gwangju", "Goteborg"]
    static let h = ["Hachioji", "Haicheng", "Haikou", "Hailun", "Haimen", "Haining", "Haiphong", "Haiyang", "Hama", "Hamamatsu", "Hamburg", "Hamhung", "Hanchuan", "Handan", "Hangzhou", "Haora", "Harare", "Harbin", "Havana", "Hechuan", "Hefei", "Hegang", "Hejian", "Helsinki", "Hengyang", "Hermosillo", "Heze", "Hezhou", "Hiroshima", "Ho Chi Minh City", "Homs", "Hong Kong", "Honghu", "Houston", "Huaian", "Huaibei", "Huainan", "Huaiyin", "Huangshi", "Huazhou", "Huixian", "Huiyang", "Huizhou", "Huludao", "Huzhou", "Ha Noi"]
    static let i = ["Ibadan", "Ilorin", "Imbaba", "Incheon", "Indianapolis", "Indore", "Irkutsk", "Islamabad", "Istanbul", "Izhevsk", "Izmir", "Icel"]
    static let j = ["Jabalpur", "Jacksonville", "Jaipur", "Jakarta", "Jalandhar", "Jammu", "Jamnagar", "Jamshedpur", "Jeddah", "Jeonju", "Jerusalem", "Jiamusi", "Jiangdu", "Jiangjin", "Jiangmen", "Jiangyan", "Jiangyin", "Jiangyou", "Jianyang", "Jiaonan", "Jiaozhou", "Jiaozuo", "Jiaxing", "Jieshou", "Jieyang", "Jilin", "Jimo", "Jingjiang", "Jingmen", "Jingzhou", "Jining", "Jinjiang", "Jintan", "Jinzhong", "Jiujiang", "Jiutai", "Jixi", "Jiyuan", "Joao Pessoa", "Jodhpur", "Johannesburg", "Jurong", "Juarez"]
    static let k = ["Kabul", "Kaduna", "Kaifeng", "Kaiping", "Kaiyuan", "Kalyan", "Kampala", "Kano", "Kanpur", "Kaohsiung", "Karachi", "Karaj", "Kathmandu", "Katowice", "Kawasaki", "Kayes", "Kayseri", "Kazan", "Kemerovo", "Kerman", "Kermanshah", "Khabarovsk", "Kharkiv", "Khartoum", "Khartoum North", "Khulna", "Kingston", "Kinshasa", "Kishinev", "Kisumu", "Kitakyushu", "Kobe", "Kochi", "Kolkata", "Konya", "Kota", "Koulikoro", "Kozhikode", "Krakow", "Krasnodar", "Krasnoyarsk", "Kuala Lumpur", "Kumamoto", "Kumasi", "Kunming", "Kunshan", "Kyiv", "Kyoto", "Kenitra", "Koln"]
    static let l = ["La Matanza", "La Paz", "La Plata", "Lagos", "Lahore", "Laiwu", "Laixi", "Laiyang", "Laizhou", "Langfang", "Langzhong", "Lanxi", "Lanzhou", "Las Vegas", "Lattakia", "Leiyang", "Leizhou", "Leling", "Leping", "Leshan", "Lianjiang", "Lianyuan", "Lianyungang", "Liaocheng", "Liaoyang", "Lichuan", "Liling", "Lilongwe", "Lima", "Linfen", "Linghai", "Lingyuan", "Linhai", "Linqing", "Linyi", "Lisbon", "Liuan", "Liuyang", "Liuzhou", "Liverpool", "Liyang", "Lomas de Zamora", "London", "Longhai", "Longkou", "Longyan", "Los Angeles", "Louisville", "Luanda", "Lucknow", "Ludhiana", "Lufeng", "Luoyang", "Lusaka", "Luzhou", "Lviv", "Lodz"]
    static let m = ["Maanshan", "Maceio", "Macheng", "Madrid", "Madurai", "Maiduguri", "Makhachkala", "Malang", "Malmo", "Managua", "Manaus", "Manchester", "Mangalore", "Manila", "Maoming", "Maputo", "Maracaibo", "Marrakech", "Marseille", "Mashhad", "Medan", "Medellín", "Meerut", "Meihekou", "Meishan", "Meknès", "Melbourne", "Memphis", "Mendoza", "Mexicali", "Mexico City", "Miami", "Mianyang", "Milan", "Miluo", "Milwaukee", "Mingguang", "Minneapolis", "Minsk", "Mogadishu", "Mombasa", "Monterrey", "Montevideo", "Montreal", "Mopti", "Moradabad", "Morelia", "Moron", "Moscow", "Mosul", "Multan", "Mumbai", "Mysore", "Malaga", "Merida", "Munchen"]
    static let n = ["Nagoya", "Nagpur", "Nairobi", "Nakhon Ratchasima", "Nakuru", "Nanchang", "Nanchong", "Nanchuan", "Nanhai", "Nanjing", "Nankang", "Nanning", "Nantong", "Nanyang", "Naples", "Nashik", "Nashville-davidson", "Natal", "Nehe", "Neijiang", "New York", "Niamey", "Niigata", "Ningbo", "Nizhny Novgorod", "Nonthaburi", "Nottingham", "Nouakchott", "Nova Iguacu", "Novokuznetsk", "Novosibirsk"]
    static let o = ["Odessa", "Okayama", "Oklahoma City", "Omdurman", "Omsk", "Oran", "Orenburg", "Orumiyeh", "Osaka", "Osasco", "Oslo", "Ottawa", "Ouagadougou"]
    static let p = ["Padang", "Palembang", "Palermo", "Panjin", "Panshi", "Panzhihua", "Paris", "Patna", "Pengzhou", "Perm", "Perth", "Peshawar", "Philadelphia", "Phnom Penh", "Phoenix", "Pingdingshan", "Pingdu", "Pingxiang", "Pizhou", "Port Elizabeth", "Port Harcourt", "Port-au-prince", "Portland", "Porto Alegre", "Poznan", "Prague", "Preston", "Pretoria", "Puebla de Zaragoza", "Puente Alto", "Pulandian", "Pune", "Puning", "Pyongyang"]
    static let q = [ "Qianjiang", "Qidong", "Qingdao", "Qingzhou", "Qinhuangdao", "Qinzhou", "Qionglai", "Qiongshan", "Qixia", "Qom", "Quanzhou", "Queretaro", "Quetta", "Quezon City", "Qufu", "Quito", "Qujing", "Quebec"]
    static let r = ["Rabat", "Raipur", "Rajkot", "Ranchi", "Rasht", "Rawalpindi", "Recife", "Renqiu", "Reynosa", "Ribeirao Prêto", "Riga", "Rio de Janeiro", "Riyadh", "Rizhao", "Rome", "Rongcheng", "Rosario", "Rostov-na-donu", "Rotterdam", "Rugao", "Ruijin"]
    static let s = ["Safi", "Sagamihara", "Saint Petersburg", "Saitama", "Sakai", "Salem", "Saltillo", "Salvador", "Sale", "Samara", "Samarinda", "Samarskaya oblast", "Samut Prakan", "San Antonio", "San Diego", "San Francisco", "San Jose", "San Juan", "San Luis Potosí", "San Miguel de Tucuman", "Santa Cruz", "Santiago", "Santiago de los Caballeros", "Santo Andre", "Santo Domingo", "Sao Bernardo do Campo", "Sao Goncalo", "Sao Jose dos Campos", "Sao Luís", "Sao Paulo", "Sapporo", "Sarajevo", "Saratov", "Seattle", "Semarang", "Sendai", "Seongnam", "Seoul", "Sevilla", "Shanghai", "Shangqiu", "Shangyu", "Shangzhi", "Shangzhou", "Shantou", "Shaoguan", "Shaoxing", "Shaoyang", "Sheffield", "Shengzhou", "Shenyang", "Shenzhen", "Shihezi", "Shijiazhuang", "Shiraz", "Shishou", "Shiyan", "Shizuoka", "Shouguang", "Shuangcheng", "Shulan", "Shunde", "Shuozhou", "Sikasso", "Singapore", "Skoplje", "Sofia", "Solapur", "Songyuan", "Songzi", "Sorocaba", "Soweto", "Srinagar", "St. Louis", "Stockholm", "Stuttgart", "Suihua", "Suining", "Suizhou", "Surabaya", "Surat", "Suwon", "Suzhou", "Suzhou", "Sydney", "Segou"]
    static let t = ["Tabriz", "Taian", "Taichung", "Tainan", "Taipei", "Taishan", "Taixing", "Taiyuan", "Taizhou", "Taizhou", "Tampa", "Tampico", "Tanger", "Tangerang", "Tangshan", "Tashkent", "Tbilisi", "Tegucigalpa", "Tehran", "Tel Aviv-yafo", "Tengzhou", "Teresina", "Thane", "The Hague", "Tianchang", "Tianjin", "Tianmen", "Tianshui", "Tijuana", "Tiruppur", "Tokyo", "Tolyatti", "Tongcheng", "Tongliao", "Tongxiang", "Tongzhou", "Torino", "Toronto", "Torreon", "Tripoli", "Trujillo", "Tunis", "Tyumen", "Tetouan"]
    static let u = ["Uberlândia", "Ufa", "Ulaanbaatar", "Ulsan", "Ulyanovsk", "Urumqi"]
    static let v = ["Vadodara", "Valencia", "Valencia", "Vancouver", "static letanasi", "Veracruz", "Vienna", "Vientiane", "Vijayawada", "Vilnius", "Visakhapatnam", "Vladivostok", "Volgograd", "Voronezh"]
    static let w = ["Wafangdian", "Wanyuan", "Warangal", "Warsaw", "Washington", "Weifang", "Weihai", "Weinan", "Wendeng", "Wenling", "Wenzhou", "Winnipeg", "Wroclaw", "Wuan", "Wuchang", "Wuchuan", "Wugang", "Wuhu", "Wujiang", "Wujin", "Wuwei", "Wuxi", "Wuxian", "Wuxue"]
    static let x = ["Xiamen", "Xiangcheng", "Xiangfan", "Xiangtan", "Xiangxiang", "Xianning", "Xiantao", "Xianyang", "Xiaogan", "Xiaoshan", "Xichang", "Xingcheng", "Xinghua", "Xingning", "Xingping", "Xingtai", "Xingyang", "Xingyi", "Xinhui", "Xinji", "Xintai", "Xinxiang", "Xinyang", "Xinyi", "Xinyi", "Xinyu", "Xinzheng", "Xishan", "Xuancheng", "Xuzhou"]
    static let y = ["Yancheng", "Yangchun", "Yangjiang", "Yangon", "Yangquan", "Yangzhou", "Yanshi", "Yantai", "Yaounde", "Yerevan", "Yibin", "Yichang", "Yicheng", "Yichun", "Yichun", "Yinchuan", "Yingcheng", "Yingde", "Yingkou", "Yiwu", "Yixing", "Yiyang", "Yizheng", "Yizhou", "Yokohama", "Yongcheng", "Yongchuan", "Yongkang", "Yongzhou", "Yuanjiang", "Yueyang", "Yuhang", "Yulin", "Yuncheng", "Yunzhou", "Yushu", "Yuyao", "Yuzhou"]
    static let z = ["Zagreb", "Zahedan", "Zamboanga", "Zaoyang", "Zaozhuang", "Zaragoza", "Zaria", "Zengcheng", "Zhangjiagang", "Zhangjiakou", "Zhangqiu", "Zhangshu", "Zhangzhou", "Zhanjiang", "Zhaodong", "Zhaotong", "Zhaoyuan", "Zhengzhou", "Zhenjiang", "Zhongshan", "Zhongxiang", "Zhoushan", "Zhuanghe", "Zhucheng", "Zhuhai", "Zhuji", "Zhuzhou", "Zibo", "Zigong", "Ziyang", "Zoucheng", "Zunyi", "Zurich"]
}
